### ISSUE TITLE
Soil Options

### ISSUE THREAD

**Issue by Finnigan0** [Quizer9O8/Strata#13]
Considering the fact that you’ve done stone types, why not do the same for soil using the silt, clay, and sand system pictured at the bottom. There could be a few uses/ mechanics added through this, certain soil types may be more fertile based on composition or certain biome types may be more inclined to have certain soil types. Another addition could be block physics based on composition, depending on percentage of silt, sand or clay the block may be affected by gravity more or less (somewhere between sand and dirt).

![36C8CFCA-032A-4A5F-812D-575648E1706F](https://user-images.githubusercontent.com/11883438/97799074-45a41800-1c77-11eb-97de-62cff8551711.jpeg)

**Comment by Quizer9O8** [comment]
I really like the idea of having different types of soils but I think this would do better as a stand-alone mod rather than being integrated in Strata itself.

**Comment by Auseawesome** [comment]
> I really like the idea of having different types of soils but I think this would do better as a stand-alone mod rather than being integrated in Strata itself.

Will you make this sort of mod? I would really like different soils as currently you can't say have like jungle soil in a plains a s it all looks the same
