### ISSUE TITLE
Stone Types generated in Vanilla worlds

### ISSUE THREAD

**Issue by Late-Night** [Quizer9O8/Strata#16]
**Describe the feature you'd like**
i'd quite like it if this mod's stone types generated in vanilla worlds too
mainly because terraforged tends to cause immense lag on my pc

**Additional Context**
Anything from pictures to links to websites and etc. to further emphasize your suggestion.

**Comment by Quizer9O8** [comment]
If I were to generate the stone types in default or modded world types other than TerraForged I would approach it in a similar way like Vanilla, [Underground Biomes](https://www.curseforge.com/minecraft/mc-mods/underground-biomes) and [Mineralogy ](https://www.curseforge.com/minecraft/mc-mods/minecraft-mineralogy) did. By doing so requires me to make major changes in the code. As for now this is out of scope and won't be done by me any time soon.
