### ISSUE TITLE
Will this get updated to 1.16.5 soon and can we have new brick textures?

### ISSUE THREAD

**Issue by Auseawesome** [Quizer9O8/Strata#17]
**Describe the feature you'd like**
I would like an update to 1.16.5 and also many different types of Bricks as this is a decoration mod and we are missing brick variety like having small bricks like bricks and large bricks like stone brick would be nice as well as having like a path texture for bricks.
**Additional Context**

https://github.com/Quizer9O8/Strata/issues/14 Similar to this but not changing brick textures, adding more

**Comment by Quizer9O8** [comment]
Sadly there's no 1.16.5 update, but in the past month @GamingCrew69 was so kind to update the mod to later versions of Minecraft. Check out [Releases](https://github.com/Quizer9O8/Strata/releases) for updated versions.
As for the brick variety this is something I still want to introduce into the mod later down the line as well.

**Comment by Auseawesome** [comment]
Thanks for your reply even after all this time. Luckily now these newer updates are incredibly useful. Thanks for the mod!
