### ISSUE TITLE
Strata layers not generating in newest build of terraforged

### ISSUE THREAD

**Issue by irksomebigfoot8** [Quizer9O8/Strata#23]
**Minecraft Version**
For example: Minecraft 1.20.1

**Forge Version**
For example: Forge - MC 1.20.1 - 47.2.16

**Description**
Latest build of ReTerraforged seem's to have broken strata layer generation.

**Comment by Quizer9O8** [comment]
Due to a bug in the latest version of ReTerraForged version 0.0.6 The strata layer where different types of rock would be doesn't appear at all. It should be fixed in version 0.0.7 once released. If not address this issue to the developer.
