### ISSUE TITLE
Incompatible with Reterraforged

### ISSUE THREAD

**Issue by autumnly24** [Quizer9O8/Strata#24]
1.20.1
Forge 47.2.16

The current remake of terraforged for modern versions is known as Reterraforged, you're able to download it via the Terraforged Discord's "Developement" channel. It is functionally pretty similar but just for modern versions.

Currently, with both mods installed, there are no strata layers that appear.

**Comment by Quizer9O8** [comment]
Due to a bug in the latest version of ReTerraForged version 0.0.6 The strata layer where different types of rock would be doesn't appear at all. It should be fixed in version 0.0.7 once released. If not address this issue to the developer.
