### ISSUE TITLE
ReTerraForged Compat (found working solution)

### ISSUE THREAD

**Issue by ColossalRenders** [Quizer9O8/Strata#25]
Add compatibility with the 1.20.1 version of ReTerraForged

**Additional Context**
https://github.com/racoonman2/ReTerraForged

**Comment by ColossalRenders** [comment]
UPDATE: works with fork https://github.com/GamingCrew69/ReTerraForged/tree/1.20.1

The original repo didn't build, but after copying the offending mixin file from the main fork of RTF it has worked perfectly so far.

**Comment by RealMichaelDino** [comment]
@ColossalRenders 
Don't mind me but would you perchance have a copy of this version of RTF that functions with Strata? I am no modder myself so I have a feeling if I tried to build the file it would probably explode lol.
Appreciated!
