### ISSUE TITLE
Add stone types to the quark:stone_tool_materials tag

### ISSUE THREAD

**Issue by azaquaz** [Quizer9O8/Strata#6]
Quark adds a feature which lets stone tools be crafted using stone, andesite, diorite, granite, and all the stone types added by Quark itself. It would be very convenient if this mod's stone types could also be used for that.

**Comment by Quizer9O8** [comment]
I'll look further into this feature of Quark and see if I can make it work.

**Comment by Quizer9O8** [comment]
Compatibility added in version [1.0.2](https://github.com/Quizer9O8/Strata/releases/tag/1.0.2).
