### ISSUE TITLE
BUG - Cobblestone variants do not drop when mined in survival mode

### ISSUE THREAD

**Issue by AzureMonument** [Quizer9O8/Strata#7]
Before reporting a bug please read [Writing Helpful Bug Reports](https://github.com/Quizer9O8/Strata/wiki/Writing-Helpful-Bug-Reports) if you haven't already
---

Minecraft 1.15.2

Forge 32.2.31

**Description**
Cobblestone stone variants do not drop when mined in survival mode, both normal and mossy versions. This is regardless of whether or not the pick used has silk touch. This also affects all stair, wall, and slab types. (To test this I used two different diamond picks (one silk touch, the other normal) in a creative testing world and switched to survival after placing two blocks of each cobblestone type and mined them. Then I tested similarly on 1 of each respective wall/stair/slab.)

**How to reproduce**
Mine any piece of cobblestone from this mod with a normal pick while in survival mode. 

**Additional information**
** do note I have the project mmo mod, but all functions relating to mining level (and any other restrictions on tool use) are disabled in entirely in the configs
![2020-07-18_11 08 15](https://user-images.githubusercontent.com/43318292/87855623-87d36480-c8e7-11ea-89fc-6b9a0e1f349b.png)

**Comment by Quizer9O8** [comment]
It turns out that the loot tables for the cobblestone variants had some errors in the code which caused it not to drop cobblestone after mining it. This should be fixed in the [latest ](https://github.com/Quizer9O8/Strata/releases/tag/1.0.3_hf-2) release now.
